default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: whislist_development

test:
  <<: *default
  database: whislist_test

production:
  <<: *default
  database: my_app_production
  url: <%= ENV["DATABASE_URL"] %>
